name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy: 
    name: Build and push docker image 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: boxmein
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@b1aeb1103e6b3b5648dbd6deaf0559919456ca6b
        with:
          context: .
          push: true
          tags: ghcr.io/boxmein/adctf_scoreboard_exporter
